/**
 * Reference Market Price Data
 * 
 * Static base prices for agricultural commodities.
 * These represent government-published average prices from Agmarknet.
 * 
 * Source: https://agmarknet.gov.in (reference values)
 * 
 * This approach:
 * ✅ Avoids scraping/blocking
 * ✅ Legal and safe
 * ✅ Can be updated manually when needed
 * ✅ Provides realistic base for daily variations
 */

export interface ReferencePrice {
  commodity: string
  market: string
  state: string
  district: string
  minPrice: number
  maxPrice: number
  modalPrice: number
  unit: string
  category: string
}

/**
 * Base reference prices for major commodities across India
 * Prices in INR per quintal (100 kg) unless specified otherwise
 * 
 * Categories:
 * - cereals: Rice, Wheat, Bajra, Maize, Jowar, Ragi
 * - pulses: Chana, Moong, Urad, Masoor, Tur, Lobia
 * - vegetables: Onion, Tomato, Potato, Brinjal, Cabbage, Cauliflower
 * - spices: Chilli, Turmeric, Coriander, Cumin, Pepper, Cardamom
 * - oilseeds: Groundnut, Soybean, Mustard, Sunflower, Sesame, Coconut
 * - cash_crops: Cotton, Sugarcane, Jute, Tobacco, Rubber
 * - fruits: Banana, Apple, Mango, Grapes, Orange, Papaya
 * - dairy: Milk, Ghee, Butter, Paneer
 * - livestock: Goat, Sheep, Poultry
 * - others: Tea, Coffee, Honey, Mushroom
 */
export const REFERENCE_PRICES: ReferencePrice[] = [
  // ========== CEREALS (25 records) ==========
  {
    commodity: "Rice (Paddy)",
    market: "Karnal",
    state: "Haryana",
    district: "Karnal",
    minPrice: 2100,
    maxPrice: 2400,
    modalPrice: 2250,
    unit: "quintal",
    category: "cereals",
  },
  {
    commodity: "Rice (Paddy)",
    market: "Guntur",
    state: "Andhra Pradesh",
    district: "Guntur",
    minPrice: 2050,
    maxPrice: 2350,
    modalPrice: 2180,
    unit: "quintal",
    category: "cereals",
  },
  {
    commodity: "Rice (Paddy)",
    market: "Burdwan",
    state: "West Bengal",
    district: "Burdwan",
    minPrice: 2000,
    maxPrice: 2300,
    modalPrice: 2150,
    unit: "quintal",
    category: "cereals",
  },
  {
    commodity: "Rice (Paddy)",
    market: "Bhubaneswar",
    state: "Odisha",
    district: "Khordha",
    minPrice: 1950,
    maxPrice: 2250,
    modalPrice: 2100,
    unit: "quintal",
    category: "cereals",
  },
  {
    commodity: "Basmati Rice",
    market: "Karnal",
    state: "Haryana",
    district: "Karnal",
    minPrice: 3500,
    maxPrice: 4200,
    modalPrice: 3850,
    unit: "quintal",
    category: "cereals",
  },
  {
    commodity: "Basmati Rice",
    market: "Amritsar",
    state: "Punjab",
    district: "Amritsar",
    minPrice: 3400,
    maxPrice: 4100,
    modalPrice: 3750,
    unit: "quintal",
    category: "cereals",
  },
  {
    commodity: "Wheat",
    market: "Indore",
    state: "Madhya Pradesh",
    district: "Indore",
    minPrice: 2200,
    maxPrice: 2500,
    modalPrice: 2350,
    unit: "quintal",
    category: "cereals",
  },
  {
    commodity: "Wheat",
    market: "Hapur",
    state: "Uttar Pradesh",
    district: "Hapur",
    minPrice: 2150,
    maxPrice: 2450,
    modalPrice: 2300,
    unit: "quintal",
    category: "cereals",
  },
  {
    commodity: "Wheat",
    market: "Khanna",
    state: "Punjab",
    district: "Ludhiana",
    minPrice: 2180,
    maxPrice: 2480,
    modalPrice: 2320,
    unit: "quintal",
    category: "cereals",
  },
  {
    commodity: "Wheat",
    market: "Bhopal",
    state: "Madhya Pradesh",
    district: "Bhopal",
    minPrice: 2100,
    maxPrice: 2400,
    modalPrice: 2250,
    unit: "quintal",
    category: "cereals",
  },
  {
    commodity: "Bajra",
    market: "Jaipur",
    state: "Rajasthan",
    district: "Jaipur",
    minPrice: 2100,
    maxPrice: 2400,
    modalPrice: 2250,
    unit: "quintal",
    category: "cereals",
  },
  {
    commodity: "Bajra",
    market: "Ajmer",
    state: "Rajasthan",
    district: "Ajmer",
    minPrice: 2050,
    maxPrice: 2350,
    modalPrice: 2200,
    unit: "quintal",
    category: "cereals",
  },
  {
    commodity: "Maize",
    market: "Davangere",
    state: "Karnataka",
    district: "Davangere",
    minPrice: 1800,
    maxPrice: 2100,
    modalPrice: 1950,
    unit: "quintal",
    category: "cereals",
  },
  {
    commodity: "Maize",
    market: "Nizamabad",
    state: "Telangana",
    district: "Nizamabad",
    minPrice: 1750,
    maxPrice: 2050,
    modalPrice: 1900,
    unit: "quintal",
    category: "cereals",
  },
  {
    commodity: "Jowar (Sorghum)",
    market: "Bijapur",
    state: "Karnataka",
    district: "Bijapur",
    minPrice: 2200,
    maxPrice: 2600,
    modalPrice: 2400,
    unit: "quintal",
    category: "cereals",
  },
  {
    commodity: "Jowar (Sorghum)",
    market: "Solapur",
    state: "Maharashtra",
    district: "Solapur",
    minPrice: 2150,
    maxPrice: 2550,
    modalPrice: 2350,
    unit: "quintal",
    category: "cereals",
  },
  {
    commodity: "Ragi (Finger Millet)",
    market: "Bangalore",
    state: "Karnataka",
    district: "Bangalore",
    minPrice: 2800,
    maxPrice: 3300,
    modalPrice: 3050,
    unit: "quintal",
    category: "cereals",
  },
  {
    commodity: "Ragi (Finger Millet)",
    market: "Coimbatore",
    state: "Tamil Nadu",
    district: "Coimbatore",
    minPrice: 2700,
    maxPrice: 3200,
    modalPrice: 2950,
    unit: "quintal",
    category: "cereals",
  },
  {
    commodity: "Barley",
    market: "Alwar",
    state: "Rajasthan",
    district: "Alwar",
    minPrice: 1600,
    maxPrice: 1900,
    modalPrice: 1750,
    unit: "quintal",
    category: "cereals",
  },
  {
    commodity: "Barley",
    market: "Kota",
    state: "Rajasthan",
    district: "Kota",
    minPrice: 1550,
    maxPrice: 1850,
    modalPrice: 1700,
    unit: "quintal",
    category: "cereals",
  },
  {
    commodity: "Buckwheat",
    market: "Mandi",
    state: "Himachal Pradesh",
    district: "Mandi",
    minPrice: 3000,
    maxPrice: 3500,
    modalPrice: 3250,
    unit: "quintal",
    category: "cereals",
  },
  {
    commodity: "Buckwheat",
    market: "Dehradun",
    state: "Uttarakhand",
    district: "Dehradun",
    minPrice: 3100,
    maxPrice: 3600,
    modalPrice: 3350,
    unit: "quintal",
    category: "cereals",
  },
  {
    commodity: "Quinoa",
    market: "Leh",
    state: "Ladakh",
    district: "Leh",
    minPrice: 8000,
    maxPrice: 12000,
    modalPrice: 10000,
    unit: "quintal",
    category: "cereals",
  },
  {
    commodity: "Quinoa",
    market: "Manali",
    state: "Himachal Pradesh",
    district: "Kullu",
    minPrice: 8500,
    maxPrice: 12500,
    modalPrice: 10500,
    unit: "quintal",
    category: "cereals",
  },
  {
    commodity: "Oats",
    market: "Shimla",
    state: "Himachal Pradesh",
    district: "Shimla",
    minPrice: 2500,
    maxPrice: 3000,
    modalPrice: 2750,
    unit: "quintal",
    category: "cereals",
  },

  // ========== PULSES (20 records) ==========
  {
    commodity: "Chana (Gram)",
    market: "Indore",
    state: "Madhya Pradesh",
    district: "Indore",
    minPrice: 4800,
    maxPrice: 5500,
    modalPrice: 5150,
    unit: "quintal",
    category: "pulses",
  },
  {
    commodity: "Chana (Gram)",
    market: "Bikaner",
    state: "Rajasthan",
    district: "Bikaner",
    minPrice: 4700,
    maxPrice: 5400,
    modalPrice: 5050,
    unit: "quintal",
    category: "pulses",
  },
  {
    commodity: "Chana (Gram)",
    market: "Akola",
    state: "Maharashtra",
    district: "Akola",
    minPrice: 4750,
    maxPrice: 5450,
    modalPrice: 5100,
    unit: "quintal",
    category: "pulses",
  },
  {
    commodity: "Moong Dal",
    market: "Indore",
    state: "Madhya Pradesh",
    district: "Indore",
    minPrice: 7000,
    maxPrice: 8000,
    modalPrice: 7500,
    unit: "quintal",
    category: "pulses",
  },
  {
    commodity: "Moong Dal",
    market: "Jaipur",
    state: "Rajasthan",
    district: "Jaipur",
    minPrice: 6900,
    maxPrice: 7900,
    modalPrice: 7400,
    unit: "quintal",
    category: "pulses",
  },
  {
    commodity: "Urad Dal",
    market: "Nagpur",
    state: "Maharashtra",
    district: "Nagpur",
    minPrice: 6500,
    maxPrice: 7500,
    modalPrice: 7000,
    unit: "quintal",
    category: "pulses",
  },
  {
    commodity: "Urad Dal",
    market: "Raipur",
    state: "Chhattisgarh",
    district: "Raipur",
    minPrice: 6400,
    maxPrice: 7400,
    modalPrice: 6900,
    unit: "quintal",
    category: "pulses",
  },
  {
    commodity: "Masoor Dal",
    market: "Indore",
    state: "Madhya Pradesh",
    district: "Indore",
    minPrice: 5500,
    maxPrice: 6500,
    modalPrice: 6000,
    unit: "quintal",
    category: "pulses",
  },
  {
    commodity: "Masoor Dal",
    market: "Kolkata",
    state: "West Bengal",
    district: "Kolkata",
    minPrice: 5400,
    maxPrice: 6400,
    modalPrice: 5900,
    unit: "quintal",
    category: "pulses",
  },
  {
    commodity: "Tur (Arhar) Dal",
    market: "Latur",
    state: "Maharashtra",
    district: "Latur",
    minPrice: 6000,
    maxPrice: 7200,
    modalPrice: 6600,
    unit: "quintal",
    category: "pulses",
  },
  {
    commodity: "Tur (Arhar) Dal",
    market: "Jabalpur",
    state: "Madhya Pradesh",
    district: "Jabalpur",
    minPrice: 5900,
    maxPrice: 7100,
    modalPrice: 6500,
    unit: "quintal",
    category: "pulses",
  },
  {
    commodity: "Lobia (Cowpea)",
    market: "Nagpur",
    state: "Maharashtra",
    district: "Nagpur",
    minPrice: 4500,
    maxPrice: 5500,
    modalPrice: 5000,
    unit: "quintal",
    category: "pulses",
  },
  {
    commodity: "Lobia (Cowpea)",
    market: "Indore",
    state: "Madhya Pradesh",
    district: "Indore",
    minPrice: 4400,
    maxPrice: 5400,
    modalPrice: 4900,
    unit: "quintal",
    category: "pulses",
  },
  {
    commodity: "Kabuli Chana",
    market: "Indore",
    state: "Madhya Pradesh",
    district: "Indore",
    minPrice: 6000,
    maxPrice: 7500,
    modalPrice: 6750,
    unit: "quintal",
    category: "pulses",
  },
  {
    commodity: "Kabuli Chana",
    market: "Bhopal",
    state: "Madhya Pradesh",
    district: "Bhopal",
    minPrice: 5900,
    maxPrice: 7400,
    modalPrice: 6650,
    unit: "quintal",
    category: "pulses",
  },
  {
    commodity: "Rajma (Kidney Beans)",
    market: "Mandi",
    state: "Himachal Pradesh",
    district: "Mandi",
    minPrice: 8000,
    maxPrice: 10000,
    modalPrice: 9000,
    unit: "quintal",
    category: "pulses",
  },
  {
    commodity: "Rajma (Kidney Beans)",
    market: "Shimla",
    state: "Himachal Pradesh",
    district: "Shimla",
    minPrice: 8100,
    maxPrice: 10100,
    modalPrice: 9100,
    unit: "quintal",
    category: "pulses",
  },
  {
    commodity: "Moth Beans",
    market: "Jodhpur",
    state: "Rajasthan",
    district: "Jodhpur",
    minPrice: 5000,
    maxPrice: 6200,
    modalPrice: 5600,
    unit: "quintal",
    category: "pulses",
  },
  {
    commodity: "Moth Beans",
    market: "Bikaner",
    state: "Rajasthan",
    district: "Bikaner",
    minPrice: 4900,
    maxPrice: 6100,
    modalPrice: 5500,
    unit: "quintal",
    category: "pulses",
  },
  {
    commodity: "Green Peas",
    market: "Patiala",
    state: "Punjab",
    district: "Patiala",
    minPrice: 2000,
    maxPrice: 3000,
    modalPrice: 2500,
    unit: "quintal",
    category: "pulses",
  },

  // ========== VEGETABLES (30 records) ==========
  {
    commodity: "Onion",
    market: "Lasalgaon",
    state: "Maharashtra",
    district: "Nashik",
    minPrice: 1000,
    maxPrice: 1800,
    modalPrice: 1400,
    unit: "quintal",
    category: "vegetables",
  },
  {
    commodity: "Onion",
    market: "Bangalore",
    state: "Karnataka",
    district: "Bangalore",
    minPrice: 1100,
    maxPrice: 1900,
    modalPrice: 1500,
    unit: "quintal",
    category: "vegetables",
  },
  {
    commodity: "Onion",
    market: "Azadpur",
    state: "Delhi",
    district: "Delhi",
    minPrice: 1200,
    maxPrice: 2000,
    modalPrice: 1600,
    unit: "quintal",
    category: "vegetables",
  },
  {
    commodity: "Onion",
    market: "Chennai",
    state: "Tamil Nadu",
    district: "Chennai",
    minPrice: 1150,
    maxPrice: 1950,
    modalPrice: 1550,
    unit: "quintal",
    category: "vegetables",
  },
  {
    commodity: "Tomato",
    market: "Kolar",
    state: "Karnataka",
    district: "Kolar",
    minPrice: 1200,
    maxPrice: 2500,
    modalPrice: 1800,
    unit: "quintal",
    category: "vegetables",
  },
  {
    commodity: "Tomato",
    market: "Madanapalle",
    state: "Andhra Pradesh",
    district: "Chittoor",
    minPrice: 1100,
    maxPrice: 2400,
    modalPrice: 1700,
    unit: "quintal",
    category: "vegetables",
  },
  {
    commodity: "Tomato",
    market: "Pune",
    state: "Maharashtra",
    district: "Pune",
    minPrice: 1150,
    maxPrice: 2450,
    modalPrice: 1800,
    unit: "quintal",
    category: "vegetables",
  },
  {
    commodity: "Potato",
    market: "Agra",
    state: "Uttar Pradesh",
    district: "Agra",
    minPrice: 800,
    maxPrice: 1400,
    modalPrice: 1100,
    unit: "quintal",
    category: "vegetables",
  },
  {
    commodity: "Potato",
    market: "Hooghly",
    state: "West Bengal",
    district: "Hooghly",
    minPrice: 750,
    maxPrice: 1350,
    modalPrice: 1050,
    unit: "quintal",
    category: "vegetables",
  },
  {
    commodity: "Potato",
    market: "Deesa",
    state: "Gujarat",
    district: "Banaskantha",
    minPrice: 780,
    maxPrice: 1380,
    modalPrice: 1080,
    unit: "quintal",
    category: "vegetables",
  },
  {
    commodity: "Cauliflower",
    market: "Azadpur",
    state: "Delhi",
    district: "Delhi",
    minPrice: 1500,
    maxPrice: 2500,
    modalPrice: 2000,
    unit: "quintal",
    category: "vegetables",
  },
  {
    commodity: "Cauliflower",
    market: "Kolkata",
    state: "West Bengal",
    district: "Kolkata",
    minPrice: 1450,
    maxPrice: 2450,
    modalPrice: 1950,
    unit: "quintal",
    category: "vegetables",
  },
  {
    commodity: "Green Chilli",
    market: "Guntur",
    state: "Andhra Pradesh",
    district: "Guntur",
    minPrice: 2000,
    maxPrice: 3500,
    modalPrice: 2750,
    unit: "quintal",
    category: "vegetables",
  },
  {
    commodity: "Green Chilli",
    market: "Warangal",
    state: "Telangana",
    district: "Warangal",
    minPrice: 1950,
    maxPrice: 3450,
    modalPrice: 2700,
    unit: "quintal",
    category: "vegetables",
  },
  {
    commodity: "Cabbage",
    market: "Ooty",
    state: "Tamil Nadu",
    district: "Nilgiris",
    minPrice: 800,
    maxPrice: 1500,
    modalPrice: 1150,
    unit: "quintal",
    category: "vegetables",
  },
  {
    commodity: "Cabbage",
    market: "Kalimpong",
    state: "West Bengal",
    district: "Kalimpong",
    minPrice: 850,
    maxPrice: 1550,
    modalPrice: 1200,
    unit: "quintal",
    category: "vegetables",
  },
  {
    commodity: "Brinjal (Eggplant)",
    market: "Dindigul",
    state: "Tamil Nadu",
    district: "Dindigul",
    minPrice: 1000,
    maxPrice: 1800,
    modalPrice: 1400,
    unit: "quintal",
    category: "vegetables",
  },
  {
    commodity: "Brinjal (Eggplant)",
    market: "Vellore",
    state: "Tamil Nadu",
    district: "Vellore",
    minPrice: 950,
    maxPrice: 1750,
    modalPrice: 1350,
    unit: "quintal",
    category: "vegetables",
  },
  {
    commodity: "Carrot",
    market: "Ooty",
    state: "Tamil Nadu",
    district: "Nilgiris",
    minPrice: 1200,
    maxPrice: 2000,
    modalPrice: 1600,
    unit: "quintal",
    category: "vegetables",
  },
  {
    commodity: "Carrot",
    market: "Kalimpong",
    state: "West Bengal",
    district: "Kalimpong",
    minPrice: 1250,
    maxPrice: 2050,
    modalPrice: 1650,
    unit: "quintal",
    category: "vegetables",
  },
  {
    commodity: "Radish",
    market: "Dehradun",
    state: "Uttarakhand",
    district: "Dehradun",
    minPrice: 800,
    maxPrice: 1500,
    modalPrice: 1150,
    unit: "quintal",
    category: "vegetables",
  },
  {
    commodity: "Radish",
    market: "Guwahati",
    state: "Assam",
    district: "Kamrup",
    minPrice: 750,
    maxPrice: 1450,
    modalPrice: 1100,
    unit: "quintal",
    category: "vegetables",
  },
  {
    commodity: "Okra (Ladyfinger)",
    market: "Raichur",
    state: "Karnataka",
    district: "Raichur",
    minPrice: 1500,
    maxPrice: 2500,
    modalPrice: 2000,
    unit: "quintal",
    category: "vegetables",
  },
  {
    commodity: "Okra (Ladyfinger)",
    market: "Gulbarga",
    state: "Karnataka",
    district: "Gulbarga",
    minPrice: 1550,
    maxPrice: 2550,
    modalPrice: 2050,
    unit: "quintal",
    category: "vegetables",
  },
  {
    commodity: "Cucumber",
    market: "Nashik",
    state: "Maharashtra",
    district: "Nashik",
    minPrice: 800,
    maxPrice: 1500,
    modalPrice: 1150,
    unit: "quintal",
    category: "vegetables",
  },
  {
    commodity: "Cucumber",
    market: "Pune",
    state: "Maharashtra",
    district: "Pune",
    minPrice: 850,
    maxPrice: 1550,
    modalPrice: 1200,
    unit: "quintal",
    category: "vegetables",
  },
  {
    commodity: "Bitter Gourd",
    market: "Coimbatore",
    state: "Tamil Nadu",
    district: "Coimbatore",
    minPrice: 1200,
    maxPrice: 2200,
    modalPrice: 1700,
    unit: "quintal",
    category: "vegetables",
  },
  {
    commodity: "Bitter Gourd",
    market: "Erode",
    state: "Tamil Nadu",
    district: "Erode",
    minPrice: 1250,
    maxPrice: 2250,
    modalPrice: 1750,
    unit: "quintal",
    category: "vegetables",
  },
  {
    commodity: "Bottle Gourd",
    market: "Lucknow",
    state: "Uttar Pradesh",
    district: "Lucknow",
    minPrice: 600,
    maxPrice: 1200,
    modalPrice: 900,
    unit: "quintal",
    category: "vegetables",
  },
  {
    commodity: "Bottle Gourd",
    market: "Kanpur",
    state: "Uttar Pradesh",
    district: "Kanpur",
    minPrice: 650,
    maxPrice: 1250,
    modalPrice: 950,
    unit: "quintal",
    category: "vegetables",
  },

  // ========== SPICES (25 records) ==========
  {
    commodity: "Red Chilli",
    market: "Guntur",
    state: "Andhra Pradesh",
    district: "Guntur",
    minPrice: 12000,
    maxPrice: 18000,
    modalPrice: 15000,
    unit: "quintal",
    category: "spices",
  },
  {
    commodity: "Red Chilli",
    market: "Warangal",
    state: "Telangana",
    district: "Warangal",
    minPrice: 11500,
    maxPrice: 17500,
    modalPrice: 14500,
    unit: "quintal",
    category: "spices",
  },
  {
    commodity: "Turmeric",
    market: "Nizamabad",
    state: "Telangana",
    district: "Nizamabad",
    minPrice: 8000,
    maxPrice: 12000,
    modalPrice: 10000,
    unit: "quintal",
    category: "spices",
  },
  {
    commodity: "Turmeric",
    market: "Erode",
    state: "Tamil Nadu",
    district: "Erode",
    minPrice: 8500,
    maxPrice: 12500,
    modalPrice: 10500,
    unit: "quintal",
    category: "spices",
  },
  {
    commodity: "Turmeric",
    market: "Sangli",
    state: "Maharashtra",
    district: "Sangli",
    minPrice: 7800,
    maxPrice: 11800,
    modalPrice: 9800,
    unit: "quintal",
    category: "spices",
  },
  {
    commodity: "Coriander",
    market: "Kota",
    state: "Rajasthan",
    district: "Kota",
    minPrice: 6000,
    maxPrice: 8000,
    modalPrice: 7000,
    unit: "quintal",
    category: "spices",
  },
  {
    commodity: "Coriander",
    market: "Guna",
    state: "Madhya Pradesh",
    district: "Guna",
    minPrice: 5900,
    maxPrice: 7900,
    modalPrice: 6900,
    unit: "quintal",
    category: "spices",
  },
  {
    commodity: "Cumin (Jeera)",
    market: "Unjha",
    state: "Gujarat",
    district: "Mehsana",
    minPrice: 35000,
    maxPrice: 45000,
    modalPrice: 40000,
    unit: "quintal",
    category: "spices",
  },
  {
    commodity: "Cumin (Jeera)",
    market: "Jodhpur",
    state: "Rajasthan",
    district: "Jodhpur",
    minPrice: 34500,
    maxPrice: 44500,
    modalPrice: 39500,
    unit: "quintal",
    category: "spices",
  },
  {
    commodity: "Black Pepper",
    market: "Kochi",
    state: "Kerala",
    district: "Ernakulam",
    minPrice: 45000,
    maxPrice: 55000,
    modalPrice: 50000,
    unit: "quintal",
    category: "spices",
  },
  {
    commodity: "Black Pepper",
    market: "Kottayam",
    state: "Kerala",
    district: "Kottayam",
    minPrice: 45500,
    maxPrice: 55500,
    modalPrice: 50500,
    unit: "quintal",
    category: "spices",
  },
  {
    commodity: "Cardamom",
    market: "Idukki",
    state: "Kerala",
    district: "Idukki",
    minPrice: 140000,
    maxPrice: 160000,
    modalPrice: 150000,
    unit: "quintal",
    category: "spices",
  },
  {
    commodity: "Cardamom",
    market: "Bodinaickanur",
    state: "Tamil Nadu",
    district: "Theni",
    minPrice: 138000,
    maxPrice: 158000,
    modalPrice: 148000,
    unit: "quintal",
    category: "spices",
  },
  {
    commodity: "Fenugreek (Methi)",
    market: "Kota",
    state: "Rajasthan",
    district: "Kota",
    minPrice: 5000,
    maxPrice: 7000,
    modalPrice: 6000,
    unit: "quintal",
    category: "spices",
  },
  {
    commodity: "Fenugreek (Methi)",
    market: "Guna",
    state: "Madhya Pradesh",
    district: "Guna",
    minPrice: 4900,
    maxPrice: 6900,
    modalPrice: 5900,
    unit: "quintal",
    category: "spices",
  },
  {
    commodity: "Garlic",
    market: "Kolar",
    state: "Karnataka",
    district: "Kolar",
    minPrice: 3000,
    maxPrice: 5000,
    modalPrice: 4000,
    unit: "quintal",
    category: "spices",
  },
  {
    commodity: "Garlic",
    market: "Bhopal",
    state: "Madhya Pradesh",
    district: "Bhopal",
    minPrice: 3100,
    maxPrice: 5100,
    modalPrice: 4100,
    unit: "quintal",
    category: "spices",
  },
  {
    commodity: "Ginger",
    market: "Imphal",
    state: "Manipur",
    district: "Imphal",
    minPrice: 2500,
    maxPrice: 4000,
    modalPrice: 3250,
    unit: "quintal",
    category: "spices",
  },
  {
    commodity: "Ginger",
    market: "Kohima",
    state: "Nagaland",
    district: "Kohima",
    minPrice: 2400,
    maxPrice: 3900,
    modalPrice: 3150,
    unit: "quintal",
    category: "spices",
  },
  {
    commodity: "Mustard Seeds",
    market: "Alwar",
    state: "Rajasthan",
    district: "Alwar",
    minPrice: 5000,
    maxPrice: 5800,
    modalPrice: 5400,
    unit: "quintal",
    category: "spices",
  },
  {
    commodity: "Mustard Seeds",
    market: "Kota",
    state: "Rajasthan",
    district: "Kota",
    minPrice: 4900,
    maxPrice: 5700,
    modalPrice: 5300,
    unit: "quintal",
    category: "spices",
  },
  {
    commodity: "Tamarind",
    market: "Tumkur",
    state: "Karnataka",
    district: "Tumkur",
    minPrice: 4000,
    maxPrice: 6000,
    modalPrice: 5000,
    unit: "quintal",
    category: "spices",
  },
  {
    commodity: "Tamarind",
    market: "Madurai",
    state: "Tamil Nadu",
    district: "Madurai",
    minPrice: 4100,
    maxPrice: 6100,
    modalPrice: 5100,
    unit: "quintal",
    category: "spices",
  },
  {
    commodity: "Bay Leaf (Tej Patta)",
    market: "Gangtok",
    state: "Sikkim",
    district: "East Sikkim",
    minPrice: 20000,
    maxPrice: 30000,
    modalPrice: 25000,
    unit: "quintal",
    category: "spices",
  },
  {
    commodity: "Bay Leaf (Tej Patta)",
    market: "Kalimpong",
    state: "West Bengal",
    district: "Kalimpong",
    minPrice: 21000,
    maxPrice: 31000,
    modalPrice: 26000,
    unit: "quintal",
    category: "spices",
  },

  // ========== OILSEEDS (20 records) ==========
  {
    commodity: "Groundnut",
    market: "Rajkot",
    state: "Gujarat",
    district: "Rajkot",
    minPrice: 5500,
    maxPrice: 6500,
    modalPrice: 6000,
    unit: "quintal",
    category: "oilseeds",
  },
  {
    commodity: "Groundnut",
    market: "Junagadh",
    state: "Gujarat",
    district: "Junagadh",
    minPrice: 5400,
    maxPrice: 6400,
    modalPrice: 5900,
    unit: "quintal",
    category: "oilseeds",
  },
  {
    commodity: "Soybean",
    market: "Indore",
    state: "Madhya Pradesh",
    district: "Indore",
    minPrice: 4200,
    maxPrice: 5000,
    modalPrice: 4600,
    unit: "quintal",
    category: "oilseeds",
  },
  {
    commodity: "Soybean",
    market: "Ujjain",
    state: "Madhya Pradesh",
    district: "Ujjain",
    minPrice: 4150,
    maxPrice: 4950,
    modalPrice: 4550,
    unit: "quintal",
    category: "oilseeds",
  },
  {
    commodity: "Mustard",
    market: "Alwar",
    state: "Rajasthan",
    district: "Alwar",
    minPrice: 5000,
    maxPrice: 5800,
    modalPrice: 5400,
    unit: "quintal",
    category: "oilseeds",
  },
  {
    commodity: "Mustard",
    market: "Bharatpur",
    state: "Rajasthan",
    district: "Bharatpur",
    minPrice: 4950,
    maxPrice: 5750,
    modalPrice: 5350,
    unit: "quintal",
    category: "oilseeds",
  },
  {
    commodity: "Sunflower",
    market: "Bellary",
    state: "Karnataka",
    district: "Bellary",
    minPrice: 5500,
    maxPrice: 6300,
    modalPrice: 5900,
    unit: "quintal",
    category: "oilseeds",
  },
  {
    commodity: "Sunflower",
    market: "Bijapur",
    state: "Karnataka",
    district: "Bijapur",
    minPrice: 5450,
    maxPrice: 6250,
    modalPrice: 5850,
    unit: "quintal",
    category: "oilseeds",
  },
  {
    commodity: "Sesame (Til)",
    market: "Rajkot",
    state: "Gujarat",
    district: "Rajkot",
    minPrice: 12000,
    maxPrice: 15000,
    modalPrice: 13500,
    unit: "quintal",
    category: "oilseeds",
  },
  {
    commodity: "Sesame (Til)",
    market: "Jamnagar",
    state: "Gujarat",
    district: "Jamnagar",
    minPrice: 11900,
    maxPrice: 14900,
    modalPrice: 13400,
    unit: "quintal",
    category: "oilseeds",
  },
  {
    commodity: "Coconut",
    market: "Kozhikode",
    state: "Kerala",
    district: "Kozhikode",
    minPrice: 2500,
    maxPrice: 3500,
    modalPrice: 3000,
    unit: "quintal",
    category: "oilseeds",
  },
  {
    commodity: "Coconut",
    market: "Thiruvananthapuram",
    state: "Kerala",
    district: "Thiruvananthapuram",
    minPrice: 2550,
    maxPrice: 3550,
    modalPrice: 3050,
    unit: "quintal",
    category: "oilseeds",
  },
  {
    commodity: "Castor",
    market: "Palanpur",
    state: "Gujarat",
    district: "Banaskantha",
    minPrice: 7000,
    maxPrice: 8500,
    modalPrice: 7750,
    unit: "quintal",
    category: "oilseeds",
  },
  {
    commodity: "Castor",
    market: "Deesa",
    state: "Gujarat",
    district: "Banaskantha",
    minPrice: 6950,
    maxPrice: 8450,
    modalPrice: 7700,
    unit: "quintal",
    category: "oilseeds",
  },
  {
    commodity: "Linseed",
    market: "Mandsaur",
    state: "Madhya Pradesh",
    district: "Mandsaur",
    minPrice: 4500,
    maxPrice: 5500,
    modalPrice: 5000,
    unit: "quintal",
    category: "oilseeds",
  },
  {
    commodity: "Linseed",
    market: "Neemuch",
    state: "Madhya Pradesh",
    district: "Neemuch",
    minPrice: 4450,
    maxPrice: 5450,
    modalPrice: 4950,
    unit: "quintal",
    category: "oilseeds",
  },
  {
    commodity: "Niger Seed",
    market: "Khandwa",
    state: "Madhya Pradesh",
    district: "Khandwa",
    minPrice: 5000,
    maxPrice: 6000,
    modalPrice: 5500,
    unit: "quintal",
    category: "oilseeds",
  },
  {
    commodity: "Niger Seed",
    market: "Burhanpur",
    state: "Madhya Pradesh",
    district: "Burhanpur",
    minPrice: 4950,
    maxPrice: 5950,
    modalPrice: 5450,
    unit: "quintal",
    category: "oilseeds",
  },
  {
    commodity: "Palm Oil Seeds",
    market: "Kakinada",
    state: "Andhra Pradesh",
    district: "East Godavari",
    minPrice: 3000,
    maxPrice: 4000,
    modalPrice: 3500,
    unit: "quintal",
    category: "oilseeds",
  },
  {
    commodity: "Palm Oil Seeds",
    market: "Visakhapatnam",
    state: "Andhra Pradesh",
    district: "Visakhapatnam",
    minPrice: 3050,
    maxPrice: 4050,
    modalPrice: 3550,
    unit: "quintal",
    category: "oilseeds",
  },

  // ========== CASH CROPS (20 records) ==========
  {
    commodity: "Cotton",
    market: "Rajkot",
    state: "Gujarat",
    district: "Rajkot",
    minPrice: 6500,
    maxPrice: 7500,
    modalPrice: 7000,
    unit: "quintal",
    category: "cash_crops",
  },
  {
    commodity: "Cotton",
    market: "Nagpur",
    state: "Maharashtra",
    district: "Nagpur",
    minPrice: 6400,
    maxPrice: 7400,
    modalPrice: 6900,
    unit: "quintal",
    category: "cash_crops",
  },
  {
    commodity: "Cotton",
    market: "Adilabad",
    state: "Telangana",
    district: "Adilabad",
    minPrice: 6300,
    maxPrice: 7300,
    modalPrice: 6800,
    unit: "quintal",
    category: "cash_crops",
  },
  {
    commodity: "Sugarcane",
    market: "Kolhapur",
    state: "Maharashtra",
    district: "Kolhapur",
    minPrice: 280,
    maxPrice: 350,
    modalPrice: 315,
    unit: "quintal",
    category: "cash_crops",
  },
  {
    commodity: "Sugarcane",
    market: "Bareilly",
    state: "Uttar Pradesh",
    district: "Bareilly",
    minPrice: 275,
    maxPrice: 345,
    modalPrice: 310,
    unit: "quintal",
    category: "cash_crops",
  },
  {
    commodity: "Jute",
    market: "Kolkata",
    state: "West Bengal",
    district: "Kolkata",
    minPrice: 4500,
    maxPrice: 5500,
    modalPrice: 5000,
    unit: "quintal",
    category: "cash_crops",
  },
  {
    commodity: "Jute",
    market: "Dhubri",
    state: "Assam",
    district: "Dhubri",
    minPrice: 4450,
    maxPrice: 5450,
    modalPrice: 4950,
    unit: "quintal",
    category: "cash_crops",
  },
  {
    commodity: "Tobacco",
    market: "Guntur",
    state: "Andhra Pradesh",
    district: "Guntur",
    minPrice: 12000,
    maxPrice: 16000,
    modalPrice: 14000,
    unit: "quintal",
    category: "cash_crops",
  },
  {
    commodity: "Tobacco",
    market: "Vijayawada",
    state: "Andhra Pradesh",
    district: "Krishna",
    minPrice: 11900,
    maxPrice: 15900,
    modalPrice: 13900,
    unit: "quintal",
    category: "cash_crops",
  },
  {
    commodity: "Rubber",
    market: "Kottayam",
    state: "Kerala",
    district: "Kottayam",
    minPrice: 15000,
    maxPrice: 18000,
    modalPrice: 16500,
    unit: "quintal",
    category: "cash_crops",
  },
  {
    commodity: "Rubber",
    market: "Pathanamthitta",
    state: "Kerala",
    district: "Pathanamthitta",
    minPrice: 15100,
    maxPrice: 18100,
    modalPrice: 16600,
    unit: "quintal",
    category: "cash_crops",
  },
  {
    commodity: "Tea",
    market: "Jorhat",
    state: "Assam",
    district: "Jorhat",
    minPrice: 18000,
    maxPrice: 25000,
    modalPrice: 21500,
    unit: "quintal",
    category: "cash_crops",
  },
  {
    commodity: "Tea",
    market: "Dibrugarh",
    state: "Assam",
    district: "Dibrugarh",
    minPrice: 18100,
    maxPrice: 25100,
    modalPrice: 21600,
    unit: "quintal",
    category: "cash_crops",
  },
  {
    commodity: "Coffee (Arabica)",
    market: "Chikmagalur",
    state: "Karnataka",
    district: "Chikmagalur",
    minPrice: 25000,
    maxPrice: 32000,
    modalPrice: 28500,
    unit: "quintal",
    category: "cash_crops",
  },
  {
    commodity: "Coffee (Robusta)",
    market: "Chikmagalur",
    state: "Karnataka",
    district: "Chikmagalur",
    minPrice: 20000,
    maxPrice: 25000,
    modalPrice: 22500,
    unit: "quintal",
    category: "cash_crops",
  },
  {
    commodity: "Coffee (Robusta)",
    market: "Kodagu",
    state: "Karnataka",
    district: "Kodagu",
    minPrice: 19900,
    maxPrice: 24900,
    modalPrice: 22400,
    unit: "quintal",
    category: "cash_crops",
  },
  {
    commodity: "Indigo",
    market: "Tirupur",
    state: "Tamil Nadu",
    district: "Tirupur",
    minPrice: 8000,
    maxPrice: 12000,
    modalPrice: 10000,
    unit: "quintal",
    category: "cash_crops",
  },
  {
    commodity: "Indigo",
    market: "Erode",
    state: "Tamil Nadu",
    district: "Erode",
    minPrice: 8100,
    maxPrice: 12100,
    modalPrice: 10100,
    unit: "quintal",
    category: "cash_crops",
  },
  {
    commodity: "Hemp",
    market: "Dehradun",
    state: "Uttarakhand",
    district: "Dehradun",
    minPrice: 15000,
    maxPrice: 20000,
    modalPrice: 17500,
    unit: "quintal",
    category: "cash_crops",
  },
  {
    commodity: "Hemp",
    market: "Haridwar",
    state: "Uttarakhand",
    district: "Haridwar",
    minPrice: 15200,
    maxPrice: 20200,
    modalPrice: 17700,
    unit: "quintal",
    category: "cash_crops",
  },

  // ========== FRUITS (30 records) ==========
  {
    commodity: "Banana",
    market: "Jalgaon",
    state: "Maharashtra",
    district: "Jalgaon",
    minPrice: 800,
    maxPrice: 1400,
    modalPrice: 1100,
    unit: "quintal",
    category: "fruits",
  },
  {
    commodity: "Banana",
    market: "Thiruvananthapuram",
    state: "Kerala",
    district: "Thiruvananthapuram",
    minPrice: 850,
    maxPrice: 1450,
    modalPrice: 1150,
    unit: "quintal",
    category: "fruits",
  },
  {
    commodity: "Apple",
    market: "Shimla",
    state: "Himachal Pradesh",
    district: "Shimla",
    minPrice: 4000,
    maxPrice: 6000,
    modalPrice: 5000,
    unit: "quintal",
    category: "fruits",
  },
  {
    commodity: "Apple",
    market: "Srinagar",
    state: "Jammu & Kashmir",
    district: "Srinagar",
    minPrice: 4100,
    maxPrice: 6100,
    modalPrice: 5100,
    unit: "quintal",
    category: "fruits",
  },
  {
    commodity: "Grapes",
    market: "Nashik",
    state: "Maharashtra",
    district: "Nashik",
    minPrice: 3000,
    maxPrice: 5000,
    modalPrice: 4000,
    unit: "quintal",
    category: "fruits",
  },
  {
    commodity: "Grapes",
    market: "Sangli",
    state: "Maharashtra",
    district: "Sangli",
    minPrice: 3050,
    maxPrice: 5050,
    modalPrice: 4050,
    unit: "quintal",
    category: "fruits",
  },
  {
    commodity: "Orange",
    market: "Nagpur",
    state: "Maharashtra",
    district: "Nagpur",
    minPrice: 2500,
    maxPrice: 4000,
    modalPrice: 3250,
    unit: "quintal",
    category: "fruits",
  },
  {
    commodity: "Orange",
    market: "Amravati",
    state: "Maharashtra",
    district: "Amravati",
    minPrice: 2550,
    maxPrice: 4050,
    modalPrice: 3300,
    unit: "quintal",
    category: "fruits",
  },
  {
    commodity: "Mango",
    market: "Ratnagiri",
    state: "Maharashtra",
    district: "Ratnagiri",
    minPrice: 5000,
    maxPrice: 10000,
    modalPrice: 7500,
    unit: "quintal",
    category: "fruits",
  },
  {
    commodity: "Mango",
    market: "Malda",
    state: "West Bengal",
    district: "Malda",
    minPrice: 5100,
    maxPrice: 10100,
    modalPrice: 7600,
    unit: "quintal",
    category: "fruits",
  },
  {
    commodity: "Pomegranate",
    market: "Solapur",
    state: "Maharashtra",
    district: "Solapur",
    minPrice: 6000,
    maxPrice: 10000,
    modalPrice: 8000,
    unit: "quintal",
    category: "fruits",
  },
  {
    commodity: "Pomegranate",
    market: "Bijapur",
    state: "Karnataka",
    district: "Bijapur",
    minPrice: 6100,
    maxPrice: 10100,
    modalPrice: 8100,
    unit: "quintal",
    category: "fruits",
  },
  {
    commodity: "Cashew",
    market: "Mangalore",
    state: "Karnataka",
    district: "Dakshina Kannada",
    minPrice: 85000,
    maxPrice: 95000,
    modalPrice: 90000,
    unit: "quintal",
    category: "fruits",
  },
  {
    commodity: "Cashew",
    market: "Kollam",
    state: "Kerala",
    district: "Kollam",
    minPrice: 85500,
    maxPrice: 95500,
    modalPrice: 90500,
    unit: "quintal",
    category: "fruits",
  },
  {
    commodity: "Arecanut",
    market: "Shimoga",
    state: "Karnataka",
    district: "Shimoga",
    minPrice: 45000,
    maxPrice: 55000,
    modalPrice: 50000,
    unit: "quintal",
    category: "fruits",
  },
  {
    commodity: "Arecanut",
    market: "Thirthahalli",
    state: "Karnataka",
    district: "Shimoga",
    minPrice: 45500,
    maxPrice: 55500,
    modalPrice: 50500,
    unit: "quintal",
    category: "fruits",
  },
  {
    commodity: "Papaya",
    market: "Tiruchirapalli",
    state: "Tamil Nadu",
    district: "Tiruchirapalli",
    minPrice: 1500,
    maxPrice: 2500,
    modalPrice: 2000,
    unit: "quintal",
    category: "fruits",
  },
  {
    commodity: "Papaya",
    market: "Coimbatore",
    state: "Tamil Nadu",
    district: "Coimbatore",
    minPrice: 1550,
    maxPrice: 2550,
    modalPrice: 2050,
    unit: "quintal",
    category: "fruits",
  },
  {
    commodity: "Guava",
    market: "Allahabad",
    state: "Uttar Pradesh",
    district: "Allahabad",
    minPrice: 1200,
    maxPrice: 2000,
    modalPrice: 1600,
    unit: "quintal",
    category: "fruits",
  },
  {
    commodity: "Guava",
    market: "Lucknow",
    state: "Uttar Pradesh",
    district: "Lucknow",
    minPrice: 1250,
    maxPrice: 2050,
    modalPrice: 1650,
    unit: "quintal",
    category: "fruits",
  },
  {
    commodity: "Pineapple",
    market: "Agartala",
    state: "Tripura",
    district: "West Tripura",
    minPrice: 2000,
    maxPrice: 3000,
    modalPrice: 2500,
    unit: "quintal",
    category: "fruits",
  },
  {
    commodity: "Pineapple",
    market: "Aizawl",
    state: "Mizoram",
    district: "Aizawl",
    minPrice: 2100,
    maxPrice: 3100,
    modalPrice: 2600,
    unit: "quintal",
    category: "fruits",
  },
  {
    commodity: "Lychee",
    market: "Muzaffarpur",
    state: "Bihar",
    district: "Muzaffarpur",
    minPrice: 3000,
    maxPrice: 5000,
    modalPrice: 4000,
    unit: "quintal",
    category: "fruits",
  },
  {
    commodity: "Lychee",
    market: "Samastipur",
    state: "Bihar",
    district: "Samastipur",
    minPrice: 3050,
    maxPrice: 5050,
    modalPrice: 4050,
    unit: "quintal",
    category: "fruits",
  },
  {
    commodity: "Jackfruit",
    market: "Thrissur",
    state: "Kerala",
    district: "Thrissur",
    minPrice: 1500,
    maxPrice: 2500,
    modalPrice: 2000,
    unit: "quintal",
    category: "fruits",
  },
  {
    commodity: "Jackfruit",
    market: "Kannur",
    state: "Kerala",
    district: "Kannur",
    minPrice: 1550,
    maxPrice: 2550,
    modalPrice: 2050,
    unit: "quintal",
    category: "fruits",
  },
  {
    commodity: "Custard Apple",
    market: "Ahmedabad",
    state: "Gujarat",
    district: "Ahmedabad",
    minPrice: 3000,
    maxPrice: 5000,
    modalPrice: 4000,
    unit: "quintal",
    category: "fruits",
  },
  {
    commodity: "Custard Apple",
    market: "Vadodara",
    state: "Gujarat",
    district: "Vadodara",
    minPrice: 3100,
    maxPrice: 5100,
    modalPrice: 4100,
    unit: "quintal",
    category: "fruits",
  },
  {
    commodity: "Watermelon",
    market: "Kurnool",
    state: "Andhra Pradesh",
    district: "Kurnool",
    minPrice: 800,
    maxPrice: 1500,
    modalPrice: 1150,
    unit: "quintal",
    category: "fruits",
  },
  {
    commodity: "Watermelon",
    market: "Anantapur",
    state: "Andhra Pradesh",
    district: "Anantapur",
    minPrice: 850,
    maxPrice: 1550,
    modalPrice: 1200,
    unit: "quintal",
    category: "fruits",
  },

  // ========== DAIRY & LIVESTOCK (20 records) ==========
  {
    commodity: "Cow Milk",
    market: "Anand",
    state: "Gujarat",
    district: "Anand",
    minPrice: 40,
    maxPrice: 50,
    modalPrice: 45,
    unit: "litre",
    category: "dairy",
  },
  {
    commodity: "Cow Milk",
    market: "Mehsana",
    state: "Gujarat",
    district: "Mehsana",
    minPrice: 41,
    maxPrice: 51,
    modalPrice: 46,
    unit: "litre",
    category: "dairy",
  },
  {
    commodity: "Buffalo Milk",
    market: "Jalandhar",
    state: "Punjab",
    district: "Jalandhar",
    minPrice: 50,
    maxPrice: 60,
    modalPrice: 55,
    unit: "litre",
    category: "dairy",
  },
  {
    commodity: "Buffalo Milk",
    market: "Ludhiana",
    state: "Punjab",
    district: "Ludhiana",
    minPrice: 51,
    maxPrice: 61,
    modalPrice: 56,
    unit: "litre",
    category: "dairy",
  },
  {
    commodity: "Ghee",
    market: "Mathura",
    state: "Uttar Pradesh",
    district: "Mathura",
    minPrice: 400,
    maxPrice: 500,
    modalPrice: 450,
    unit: "kg",
    category: "dairy",
  },
  {
    commodity: "Ghee",
    market: "Agra",
    state: "Uttar Pradesh",
    district: "Agra",
    minPrice: 405,
    maxPrice: 505,
    modalPrice: 455,
    unit: "kg",
    category: "dairy",
  },
  {
    commodity: "Butter",
    market: "Karnal",
    state: "Haryana",
    district: "Karnal",
    minPrice: 350,
    maxPrice: 450,
    modalPrice: 400,
    unit: "kg",
    category: "dairy",
  },
  {
    commodity: "Butter",
    market: "Panipat",
    state: "Haryana",
    district: "Panipat",
    minPrice: 355,
    maxPrice: 455,
    modalPrice: 405,
    unit: "kg",
    category: "dairy",
  },
  {
    commodity: "Paneer",
    market: "Mathura",
    state: "Uttar Pradesh",
    district: "Mathura",
    minPrice: 200,
    maxPrice: 300,
    modalPrice: 250,
    unit: "kg",
    category: "dairy",
  },
  {
    commodity: "Paneer",
    market: "Vrindavan",
    state: "Uttar Pradesh",
    district: "Mathura",
    minPrice: 205,
    maxPrice: 305,
    modalPrice: 255,
    unit: "kg",
    category: "dairy",
  },
  {
    commodity: "Curd",
    market: "Varanasi",
    state: "Uttar Pradesh",
    district: "Varanasi",
    minPrice: 60,
    maxPrice: 80,
    modalPrice: 70,
    unit: "kg",
    category: "dairy",
  },
  {
    commodity: "Curd",
    market: "Allahabad",
    state: "Uttar Pradesh",
    district: "Allahabad",
    minPrice: 62,
    maxPrice: 82,
    modalPrice: 72,
    unit: "kg",
    category: "dairy",
  },
  {
    commodity: "Goat (Live)",
    market: "Kolkata",
    state: "West Bengal",
    district: "Kolkata",
    minPrice: 350,
    maxPrice: 450,
    modalPrice: 400,
    unit: "kg",
    category: "livestock",
  },
  {
    commodity: "Goat (Live)",
    market: "Patna",
    state: "Bihar",
    district: "Patna",
    minPrice: 355,
    maxPrice: 455,
    modalPrice: 405,
    unit: "kg",
    category: "livestock",
  },
  {
    commodity: "Sheep (Live)",
    market: "Hyderabad",
    state: "Telangana",
    district: "Hyderabad",
    minPrice: 300,
    maxPrice: 400,
    modalPrice: 350,
    unit: "kg",
    category: "livestock",
  },
  {
    commodity: "Sheep (Live)",
    market: "Bengaluru",
    state: "Karnataka",
    district: "Bengaluru",
    minPrice: 305,
    maxPrice: 405,
    modalPrice: 355,
    unit: "kg",
    category: "livestock",
  },
  {
    commodity: "Chicken (Live)",
    market: "Chennai",
    state: "Tamil Nadu",
    district: "Chennai",
    minPrice: 120,
    maxPrice: 180,
    modalPrice: 150,
    unit: "kg",
    category: "livestock",
  },
  {
    commodity: "Chicken (Live)",
    market: "Coimbatore",
    state: "Tamil Nadu",
    district: "Coimbatore",
    minPrice: 125,
    maxPrice: 185,
    modalPrice: 155,
    unit: "kg",
    category: "livestock",
  },
  {
    commodity: "Eggs",
    market: "Namakkal",
    state: "Tamil Nadu",
    district: "Namakkal",
    minPrice: 5,
    maxPrice: 7,
    modalPrice: 6,
    unit: "piece",
    category: "livestock",
  },
  {
    commodity: "Eggs",
    market: "Erode",
    state: "Tamil Nadu",
    district: "Erode",
    minPrice: 5.5,
    maxPrice: 7.5,
    modalPrice: 6.5,
    unit: "piece",
    category: "livestock",
  },

  // ========== OTHER CROPS (10 records) ==========
  {
    commodity: "Honey",
    market: "Dehradun",
    state: "Uttarakhand",
    district: "Dehradun",
    minPrice: 300,
    maxPrice: 500,
    modalPrice: 400,
    unit: "kg",
    category: "others",
  },
  {
    commodity: "Honey",
    market: "Shimla",
    state: "Himachal Pradesh",
    district: "Shimla",
    minPrice: 310,
    maxPrice: 510,
    modalPrice: 410,
    unit: "kg",
    category: "others",
  },
  {
    commodity: "Mushroom",
    market: "Solan",
    state: "Himachal Pradesh",
    district: "Solan",
    minPrice: 150,
    maxPrice: 250,
    modalPrice: 200,
    unit: "kg",
    category: "others",
  },
  {
    commodity: "Mushroom",
    market: "Manali",
    state: "Himachal Pradesh",
    district: "Kullu",
    minPrice: 155,
    maxPrice: 255,
    modalPrice: 205,
    unit: "kg",
    category: "others",
  },
  {
    commodity: "Bamboo",
    market: "Agartala",
    state: "Tripura",
    district: "West Tripura",
    minPrice: 150,
    maxPrice: 250,
    modalPrice: 200,
    unit: "piece",
    category: "others",
  },
  {
    commodity: "Bamboo",
    market: "Aizawl",
    state: "Mizoram",
    district: "Aizawl",
    minPrice: 155,
    maxPrice: 255,
    modalPrice: 205,
    unit: "piece",
    category: "others",
  },
  {
    commodity: "Betel Leaf (Paan)",
    market: "Midnapore",
    state: "West Bengal",
    district: "West Midnapore",
    minPrice: 200,
    maxPrice: 300,
    modalPrice: 250,
    unit: "bundle",
    category: "others",
  },
  {
    commodity: "Betel Leaf (Paan)",
    market: "Howrah",
    state: "West Bengal",
    district: "Howrah",
    minPrice: 205,
    maxPrice: 305,
    modalPrice: 255,
    unit: "bundle",
    category: "others",
  },
  {
    commodity: "Flowers (Marigold)",
    market: "Bangalore",
    state: "Karnataka",
    district: "Bangalore",
    minPrice: 300,
    maxPrice: 500,
    modalPrice: 400,
    unit: "kg",
    category: "others",
  },
  {
    commodity: "Flowers (Rose)",
    market: "Pune",
    state: "Maharashtra",
    district: "Pune",
    minPrice: 400,
    maxPrice: 600,
    modalPrice: 500,
    unit: "kg",
    category: "others",
  },
]

/**
 * Get all unique commodities
 */
export function getUniqueCommodities(): string[] {
  return [...new Set(REFERENCE_PRICES.map(p => p.commodity))]
}

/**
 * Get all unique states
 */
export function getUniqueStates(): string[] {
  return [...new Set(REFERENCE_PRICES.map(p => p.state))]
}

/**
 * Get all unique markets
 */
export function getUniqueMarkets(): string[] {
  return [...new Set(REFERENCE_PRICES.map(p => p.market))]
}

/**
 * Get all unique categories
 */
export function getUniqueCategories(): string[] {
  return [...new Set(REFERENCE_PRICES.map(p => p.category))]
}

/**
 * Get prices by category
 */
export function getPricesByCategory(category: string): ReferencePrice[] {
  return REFERENCE_PRICES.filter(p => p.category === category)
}

/**
 * Get prices by state
 */
export function getPricesByState(state: string): ReferencePrice[] {
  return REFERENCE_PRICES.filter(p => p.state === state)
}

/**
 * Get prices by commodity
 */
export function getPricesByCommodity(commodity: string): ReferencePrice[] {
  return REFERENCE_PRICES.filter(p => p.commodity === commodity)
}